### ISSUE TITLE
Práctica_Diseño de TextBox personalizado

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Anthony4523#2]
[Práctica 2__Diseño de TexBox personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Anthony4523/files/6333102/Practica.2__Diseno.de.TexBox.personalizado.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Israel Nicolás, Uzías López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
